create table if not exists whopipe_video_views (
    view_id integer primary key generated by default as identity,
    vide_name text not null,
    region text not null,
    date_viewed timestamp default now() not null
);

DROP TYPE IF EXISTS department;
CREATE TYPE department AS ENUM (
    'Electronics',
    'Cleaning',
    'Grocery',
    'Furniture',
    'Stationery',
    'Clothing',
    'DIY',
    'Sports',
    'Homeware',
    'Games',
    'Transport'
);

create table if not exists amazong_products(
    product_id INTEGER PRIMARY KEY generated by default as identity,
    name text not null,
    price decimal(12,2) not null,
    image text,
    category department not null
)
